### ISSUE TITLE
ModuleNotFoundError: No module named 'distmesh._distance_functions?

### ISSUE THREAD

**Issue by Feihongzhu** [bfroehle/pydistmesh#17]
Hello, thank you very much for your work! I successfully installed pydistmesh, but when importing distmesh in cmd, the following problems occur：
`>>> import distmesh
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "E:\Internship\pydistmesh-master\distmesh\__init__.py", line 24, in <module>
    from distmesh.distance_functions import *
  File "E:\Internship\pydistmesh-master\distmesh\distance_functions.py", line 71, in <module>
    from distmesh._distance_functions import dellipse
ModuleNotFoundError: No module named 'distmesh._distance_functions`

**Comment by Feihongzhu** [comment]
Why do I install pip successfully, and I still get this error ?
my system are windows10, python 3.7 , cmake and mingw64 , and I put those lapack/lapacke/blas.{dll/lib} to ./anaconda/libs/.

**Comment by Fred-Dragon** [comment]
There's an error in the source code, you need to change _distance_functions.pyx into _distance_functions.py
